### ISSUE TITLE
README에 수정이 필요합니다. `pafts.save(dic=dic, output_name='text.json')`

### ISSUE THREAD

**Issue by popop098** [harmlessman/PAFTS#1]
![image](https://github.com/harmlessman/PAFTS/assets/53284350/51ea28d0-99e2-4bf1-b7a0-72e94cf754f2)
![image](https://github.com/harmlessman/PAFTS/assets/53284350/02a2171b-86bf-43bf-811b-2bd1abff1e1e)

pafts.save(dic=dic, output_name='text.json') 이 코드가 위 스샷처럼 README와 실 코드가 서로 다릅니다.
pafts.save(dic=dic, file_name='text.json')으로 README에 수정해야할듯합니다.

**Comment by harmlessman** [comment]
확인해보니 파라미터 이름이 다르네요. 
알려주셔서 감사합니다! (바로 수정 완료) 👍
